name: CI - macOS
on: [pull_request, push]

jobs:
  ci:
    strategy:
      matrix:
        include:
          - arch: x86
            os: macos-13
            libt_version: "v1.2.19"
            qbt_gui: "GUI=ON"
            brew_install_dir: "/usr/local"
          - arch: arm
            os: macos-14
            libt_version: "v1.2.19"
            qbt_gui: "GUI=ON"
            brew_install_dir: "/opt/homebrew"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: macOS ${{ matrix.arch }} Build

    env:
      boost_path: "${{ github.workspace }}/../boost"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ runner.os }}

      - name: Install dependencies
        run: |
          brew update > /dev/null
          brew install \
            cmake ninja \
            openssl@1.1 qt@5 zlib
          brew link --force \
            qt@5
          # workaround for cmake + Qt
          sudo ln -s ${{ matrix.brew_install_dir }}/opt/qt@5/mkspecs ${{ matrix.brew_install_dir }}/mkspecs
          sudo ln -s ${{ matrix.brew_install_dir }}/opt/qt@5/plugins ${{ matrix.brew_install_dir }}/plugins
          echo "OPENSSL_ROOT_DIR=${{ matrix.brew_install_dir }}/opt/openssl@1.1" >> $GITHUB_ENV

      - name: Install boost
        run: |
          curl \
            -L \
            -o "${{ runner.temp }}/boost.tar.bz2" \
            "https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2"
          tar -xf "${{ runner.temp }}/boost.tar.bz2" -C "${{ github.workspace }}/.."
          mv "${{ github.workspace }}/.."/boost_* "${{ env.boost_path }}"

      - name: Install libtorrent
        run: |
          git clone --branch ${{ matrix.libt_version }} --depth 1 https://github.com/arvidn/libtorrent.git
          cd libtorrent
          git submodule update --init --recursive
          export PATH="/usr/lib/ccache:${{ matrix.brew_install_dir }}/opt/ccache/libexec:$PATH"
          cmake \
            -B build \
            -G "Ninja" \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DBOOST_ROOT="${{ env.boost_path }}" \
            -Ddeprecated-functions=OFF \
            -DOPENSSL_ROOT_DIR="$OPENSSL_ROOT_DIR"
          cmake --build build
          sudo cmake --install build

      - name: Build qBittorrent
        run: |
          export PATH="/usr/lib/ccache:${{ matrix.brew_install_dir }}/opt/ccache/libexec:$PATH"
          cmake \
            -B build \
            -G "Ninja" \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -D${{ matrix.qbt_gui }} \
            -DBOOST_ROOT="${{ env.boost_path }}" \
            -DVERBOSE_CONFIGURE=ON \
            -DOPENSSL_ROOT_DIR="$OPENSSL_ROOT_DIR"
          cmake --build build

      - name: Prepare build artifacts
        run: |
          # create .dmg
          appName="qbittorrent"
          if [ "${{ matrix.qbt_gui }}" = "GUI=OFF" ]; then
            appName="qbittorrent-nox"
          fi
          pushd build
          macdeployqt "$appName.app" -dmg -no-strip
          popd
          # prepare upload folder
          mkdir upload
          cp "build/$appName.dmg" upload
          mkdir upload/cmake
          cp build/compile_commands.json upload/cmake
          mkdir upload/cmake/libtorrent
          cp libtorrent/build/compile_commands.json upload/cmake/libtorrent

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qBittorrent-CI_macOS_${{ matrix.qbt_gui }}_libtorrent-${{ matrix.libt_version }}_${{ matrix.arch }}
          path: upload
