name: CI - Windows
on: [pull_request, push]

env:
  VCPKG_COMMIT: 84bab45d415d22042bd0b9081aea57f362da3f35 # 2025.12.12, Qt 5.15.18
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}\.cache\vcpkg\archives

jobs:
  ci:
    name: Build (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            runner: windows-2022
            target_arch: x64
            vcvars: vcvars64.bat
            vcpkg_triplet: x64-windows-static-release
          - arch: arm64
            runner: windows-11-arm
            target_arch: arm64
            vcvars: vcvarsarm64.bat
            vcpkg_triplet: arm64-windows-static-release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install build tools
        run: |
          choco install ninja

      # use the preinstalled vcpkg from image
      # https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#package-management
      - name: Setup vcpkg environment
        run: |
          if (-not $env:VCPKG_INSTALLATION_ROOT) {
            $env:VCPKG_INSTALLATION_ROOT = "C:/vcpkg"
          }
          git -C "$env:VCPKG_INSTALLATION_ROOT" fetch --depth=1 origin $env:VCPKG_COMMIT
          git -C "$env:VCPKG_INSTALLATION_ROOT" checkout --force $env:VCPKG_COMMIT
          & "$env:VCPKG_INSTALLATION_ROOT/bootstrap-vcpkg.bat" -disableMetrics
          "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV
          "VCPKG_FEATURE_FLAGS=manifests,versions" >> $env:GITHUB_ENV
          & "$env:VCPKG_INSTALLATION_ROOT/vcpkg.exe" version

      # tell vcpkg to only build Release variants of the dependencies
      - name: Configure vcpkg triplet overlay
        run: |
          New-Item `
            -Path "${{ github.workspace }}" `
            -Name "triplets_overlay" `
            -ItemType Directory
          @"
          set(VCPKG_TARGET_ARCHITECTURE ${{ matrix.target_arch }})
          set(VCPKG_CRT_LINKAGE static)
          set(VCPKG_LIBRARY_LINKAGE static)
          set(VCPKG_BUILD_TYPE release)
          "@ | Set-Content "${{ github.workspace }}/triplets_overlay/${{ matrix.vcpkg_triplet }}.cmake"

      - name: Cache vcpkg binary archives
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: vcpkg-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.vcpkg_triplet }}-${{ env.VCPKG_COMMIT }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json', 'vcpkg/**', 'triplets_overlay/*.cmake', '.github/workflows/ci_windows.yaml') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.vcpkg_triplet }}-${{ env.VCPKG_COMMIT }}-
            vcpkg-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.vcpkg_triplet }}-

      # clear buildtrees after each package installation to reduce disk space requirements
      - name: Install dependencies
        run: |
          & "$env:VCPKG_ROOT/vcpkg.exe" install `
            --x-manifest-root="${{ github.workspace }}" `
            --triplet=${{ matrix.vcpkg_triplet }} `
            --host-triplet=${{ matrix.vcpkg_triplet }} `
            --overlay-ports="${{ github.workspace }}/vcpkg" `
            --overlay-triplets="${{ github.workspace }}/triplets_overlay" `
            --clean-after-build

      - name: Build qBittorrent
        shell: cmd
        run: |
          set "CI_VCPKG_ROOT=%VCPKG_ROOT%"
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\${{ matrix.vcvars }}"
          set "VCPKG_ROOT=%CI_VCPKG_ROOT%"
          cmake ^
            -B build ^
            -G "Ninja" ^
            -DCMAKE_BUILD_TYPE=RelWithDebInfo ^
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ^
            -DCMAKE_TOOLCHAIN_FILE="%VCPKG_ROOT%/scripts/buildsystems/vcpkg.cmake" ^
            -DMSVC_RUNTIME_DYNAMIC=OFF ^
            -DVCPKG_MANIFEST_MODE=ON ^
            -DVCPKG_MANIFEST_DIR="${{ github.workspace }}" ^
            -DVCPKG_OVERLAY_PORTS="${{ github.workspace }}/vcpkg" ^
            -DVCPKG_OVERLAY_TRIPLETS="${{ github.workspace }}/triplets_overlay" ^
            -DVCPKG_TARGET_TRIPLET=${{ matrix.vcpkg_triplet }} ^
            -DVCPKG_HOST_TRIPLET=${{ matrix.vcpkg_triplet }} ^
            -DVERBOSE_CONFIGURE=ON ^
            --graphviz=build/target_graph.dot
          cmake --build build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: qBittorrent-CI_Windows-${{ matrix.arch }}
          path: |
            build/compile_commands.json
            build/qbittorrent.exe
            build/qbittorrent.pdb
            build/target_graph.dot
            dist/windows/qt.conf
