name: CI - Windows
on: [pull_request, push]

jobs:
  ci:
    name: Build (x64)
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install build tools
        run: |
          choco install ninja
          Invoke-Expression (Invoke-WebRequest 'https://xmake.io/psget.text' -UseBasicParsing).Content
          xmake --version
          xrepo --version

      - name: Cache xrepo packages
        uses: actions/cache@v4
        with:
          path: ~/.xmake
          key: xrepo-windows-x64-${{ hashFiles('cmake/XrepoDependencies.cmake', 'cmake/xrepo-packages/xmake.lua') }}
          restore-keys: |
            xrepo-windows-x64-

      - name: Build qBittorrent
        shell: cmd
        run: |
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake ^
            -B build ^
            -G "Ninja" ^
            -DCMAKE_BUILD_TYPE=RelWithDebInfo ^
            -DCMAKE_EXE_LINKER_FLAGS=Mpr.lib ^
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ^
            -DCMAKE_PROJECT_INCLUDE=%CD%/cmake/StaticQtPlugins.cmake ^
            -DMSVC_RUNTIME_DYNAMIC=OFF ^
            -DUSE_XREPO=ON ^
            -DVERBOSE_CONFIGURE=ON ^
            --graphviz=build/target_graph.dot
          cmake --build build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: qBittorrent-CI_Windows-x64
          path: |
            build/compile_commands.json
            build/qbittorrent.exe
            build/qbittorrent.pdb
            build/target_graph.dot
            dist/windows/qt.conf
